set(SOURCES
	src/Game/Config.cpp
	src/Game/Config.h
	src/Game/Meta.cpp
	src/Game/Meta.h
	src/Game/MetaData.cpp
	src/Game/MetaData.h
	src/Game/Presets.cpp
	src/Game/Presets.h
	src/PCH.h
	src/Papyrus/Papyrus.cpp
	src/Papyrus/Papyrus.h
	src/Papyrus/PapyrusActor.h
	src/Papyrus/PapyrusSettings.h
	src/Papyrus/PapyrusUtil.h
	src/STL.h
	src/Serialization/Event.h
	src/Serialization/Manager.cpp
	src/Serialization/Manager.h
	src/Util.h
	src/main.cpp
)
